inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'lib/flapjack-diner.rb'

# doesn't handle multi-file state
Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space