language: ruby
rvm:
- '2.0'
- '2.1'
- '2.2'
script: "bundle exec rspec"
notifications:
  irc:
    channels:
      - 'irc.freenode.net#flapjack'
    template:
      - '%{message} %{repository}#%{build_number} (%{branch} - %{commit} : %{author})'
  hipchat:
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
        (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
    rooms:
      secure: BfENxsVOSS6YKJn/kMr8ctXTvOvZHHlpgRN8AWshCEEaorPwFlCwlQuEYz+DSR7COjwLNZav5xnTFRaPkcCG8wc4ztMgSdv9XkrGjwJHxEEIzsjPT556LtLF4d8U2Di1MNsD6YGU7kvvzhh5hAPpEn0LBGhYlz+TCv+XCjI8/6I=
